import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}
      >
        <main className="h-screen border p-4 flex flex-col mx-auto justify-between w-full md:max-w-[80%]">
          <MantineProvider>
            <Header />
            <section className="flex flex-col items-center justify-start text-3xl p-5 border rounded-lg h-full w-full text-center my-3">
              {children}
            </section>
            <Footer />
          </MantineProvider>
        </main>
      </body>
    </html>
  );
}
